import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
    SidebarProvider,
    SidebarTrigger,
} from "@/registry/complex-sidebar/complex-sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}
            >
                <SidebarProvider defaultOpen>
                    <AppSidebar />
                    <main className="w-full">{children}</main>
                </SidebarProvider>
            </body>
        </html>
    );
}
