name: Build And Release

on:
    push:
        branches:
            - main
        paths-ignore:
            - "README.md"
            - "LICENSE"
            - ".github/**"

jobs:
    docker:
        runs-on: ubuntu-24.04-arm
        timeout-minutes: 30 # Add timeout
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  buildkitd-flags: --debug # Add debug logging

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/arm64
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/ui:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Trigger Coolify deployment
              run: |
                  curl --request GET '${{ secrets.DEPLOY_WEBHOOK_URL }}' --header 'Authorization: Bearer ${{ secrets.DEPLOY_KEY }}'
